---
incline:
  gcs_bucket: robotblake-sandbox
  single_page_app: true
  prefix: incline
bucket-time:
  gcs_bucket: bucket-time
  single_page_app: false
etl-graph:
  gcs_bucket: etl-graph
  single_page_app: true
  prefix: site
pibal:
  gcs_bucket: mozanalysis
  single_page_app: false
fenix-migration:
  gcs_bucket: fenix-migration
  single_page_app: false
data-club-demo:
  gcs_bucket: data-club-demo-project-1
partybal:
  gcs_bucket: partybal
  single_page_app: false
numbers-that-matter-prototype:
  gcs_bucket: numbers-that-matter-prototype 
  single_page_app: false
