---
incline:
  gcs_bucket: robotblake-sandbox
  single_page_app: true
  prefix: incline
wlach-test:
  gcs_bucket: wlach-test-gcs
  single_page_app: false
bucket-time:
  gcs_bucket: bucket-time
  single_page_app: false
etl-graph:
  gcs_bucket: etl-graph
  single_page_app: true
  prefix: site
