---
incline:
  gcs_bucket: robotblake-sandbox
  single_page_app: true
  prefix: incline
bucket-time:
  gcs_bucket: bucket-time
  single_page_app: false
etl-graph:
  gcs_bucket: etl-graph
  single_page_app: true
  prefix: site
  subdomain: true
pibal:
  gcs_bucket: mozanalysis
  single_page_app: false
fenix-migration:
  gcs_bucket: fenix-migration
  single_page_app: false
data-club-demo:
  gcs_bucket: data-club-demo-project-1
  public: true
  subdomain: true
partybal:
  gcs_bucket: partybal
  single_page_app: false
numbers-that-matter:
  gcs_bucket: mozilla-desktop-funnel-prototype
  single_page_app: false
mobile-mau-2020:
  gcs_bucket: mau-dashboard
  prefix: mobile-mau-2020
desktop-mau-dau-tier1-2020:
  gcs_bucket: mau-dashboard
  prefix: desktop-mau-dau-tier1-2020
mps-deploys:
  gcs_bucket: monitoring-queries
  prefix: static
  public: true
fission-experiment-monitoring-dashboard:
  gcs_bucket: fission-experiment-monitoring-dashboard
glean-dictionary:
  gcs_bucket: glean-dictionary-dev
  single_page_app: true
  public: true
  subdomain: true
webrender-ds-283:
  gcs_bucket: moz-fx-ds-283
  prefix: sguha/ds_283
  public: true
data-health-monitor:
  gcs_bucket: data-health-monitor
  prefix: static
